name: GSAM

base_optim: SGD
SGD:
  lr: 0.1
  weight_decay: 1e-3
  momentum: 0.9

AdamW:
  lr: 0.1
  weight_decay: 1e-3
  momentum: 0.9

rho: 0.15
alpha: 0.01
use_closure: True
single_bn_stats: True
sync_perturbaton: False